import type { Language } from "@/lib/i18n";

export const AUTH_COPY = {
  en: {
    productLabel: "Notes",
    loginTitle: "Write and organize notes",
    loginDescription: "Write notes and organize them in folders.",
    loginFeatureOne: "Choose how to write",
    loginFeatureOneDescription: "Write or edit Markdown at any time.",
    loginFeatureTwo: "Keep notes together",
    loginFeatureTwoDescription: "Group notes in folders and search their contents.",
    signInTitle: "Sign in",
    signInDescription: "Open your Nota notes.",
    emailLabel: "Email",
    emailPlaceholder: "name@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Password",
    forgotPassword: "Forgot password?",
    signIn: "Sign in",
    signingIn: "Signing in…",
    noAccount: "New to Nota?",
    createAccount: "Create account",
    unverifiedNotice: "Verify your email before signing in.",
    verifyEmail: "Go to email verification",
    invalidLogin: "Email or password is incorrect. Check them and try again.",
    loginInvalidRequest: "Enter a valid email and password.",
    loginRateLimited: "Too many attempts. Wait a moment and try again.",
    loginError: "Could not sign in. Check your connection and try again.",
    registerTitle: "Create an account",
    registerDescription: "Keep your notes in one place.",
    registerFormDescription: "Create an account to start writing.",
    registerFeatureOne: "Search notes",
    registerFeatureOneDescription: "Find words in note titles and content.",
    registerFeatureTwo: "Share a note",
    registerFeatureTwoDescription: "Create a link when you want others to read a note.",
    nameLabel: "Name",
    namePlaceholder: "Your name",
    createAccountContinue: "Create account",
    creatingAccount: "Creating account…",
    hasAccount: "Already have an account?",
    signInLink: "Sign in",
    verificationNotice: "We’ll email you a 6-digit verification code.",
    passwordMinLength: "At least 8 characters",
    passwordWeak: "Weak",
    passwordFair: "Fair",
    passwordGood: "Good",
    passwordStrong: "Strong",
    emailAlreadyUsed: "This email is already in use. Sign in or use another email.",
    registerInvalid: "Check the email, name, and password, then try again.",
    registerRateLimited: "Too many attempts. Wait a moment and try again.",
    registerEmailUnavailable: "Could not send the verification email. Try again later.",
    registerError: "Could not create your account. Check your connection and try again.",
    resetTitle: "Reset password",
    resetDescription: "We’ll email you a 6-digit code.",
    sendResetCode: "Send reset code",
    sending: "Sending…",
    verificationCode: "6-digit code",
    newPassword: "New password",
    setNewPassword: "Set new password",
    resetSuccess: "Password changed. You can sign in now.",
    resetRequestSuccess: "If the address is registered, you’ll receive a reset code.",
    resetInvalidCode: "That code is invalid or expired. Request a new code and try again.",
    resetRateLimited: "Too many attempts. Wait a moment and try again.",
    resetError: "Could not reset your password. Check the details and try again.",
    backToSignIn: "Back to sign in",
    verifyTitle: "Verify your email",
    verifyDescription: "Enter the 6-digit code sent to your email.",
    verifyCode: "Verification code",
    verify: "Verify email",
    verifying: "Verifying…",
    resendCode: "Send a new code",
    resendingCode: "Sending…",
    verificationSuccess: "Email verified. Signing you in…",
    verificationError: "Could not verify this code. Check it and try again.",
    verificationRateLimited: "Too many attempts. Wait a moment and try again.",
    resendSuccess: "If the address needs verification, a new code will be sent.",
    resendError: "Could not send a new code. Try again later.",
    oauthInvalidTitle: "Invalid connection request",
    oauthInvalidDescription: "The connection details are incomplete or do not match the registered app.",
    oauthSignInTitle: "Sign in to connect",
    oauthSignInDescription: "{client} wants to connect to your notes. Sign in to review the request.",
    oauthAllowTitle: "Allow {client} to connect?",
    oauthAccount: "Account",
    oauthRedirect: "Redirect address",
    oauthPermissions: "Access requested",
    oauthReadTitle: "Read and search notes",
    oauthReadDescription: "View your notes and search their contents.",
    oauthWriteTitle: "Create and edit notes",
    oauthWriteDescription: "Create notes, change their content, and manage sharing.",
    oauthFoldersTitle: "Manage folders",
    oauthFoldersDescription: "Create, rename, and delete folders.",
    deny: "Deny",
    allow: "Allow",
    authorizing: "Authorizing…",
    oauthNetworkError: "Could not process the request. Check your connection and try again.",
    oauthError: "Could not process the request. Return to the app and try again.",
    oauthSecurity: "PKCE S256 protects this request. You can revoke access in Settings → MCP.",
    loading: "Loading…",
    showPassword: "Show password",
    hidePassword: "Hide password",
    footer: "Nota · Notes",
    sharedNote: "Shared note",
    sharedNoteUnavailableTitle: "This note is unavailable",
    sharedNoteUnavailable: "It may no longer be shared, or the link may be incorrect.",
    openNota: "Open Nota",
    backToNota: "Back to Nota",
  },
  th: {
    productLabel: "โน้ต",
    loginTitle: "เขียนและจัดการโน้ต",
    loginDescription: "เขียนโน้ตและจัดไว้ในโฟลเดอร์",
    loginFeatureOne: "เลือกวิธีเขียน",
    loginFeatureOneDescription: "เลือกโหมดเขียน หรือแก้ Markdown ได้ทุกเมื่อ",
    loginFeatureTwo: "จัดโน้ตเป็นหมวดหมู่",
    loginFeatureTwoDescription: "จัดโน้ตในโฟลเดอร์และค้นหาจากเนื้อหา",
    signInTitle: "เข้าสู่ระบบ",
    signInDescription: "เปิดโน้ตของคุณใน Nota",
    emailLabel: "อีเมล",
    emailPlaceholder: "name@example.com",
    passwordLabel: "รหัสผ่าน",
    passwordPlaceholder: "รหัสผ่าน",
    forgotPassword: "ลืมรหัสผ่าน?",
    signIn: "เข้าสู่ระบบ",
    signingIn: "กำลังเข้าสู่ระบบ…",
    noAccount: "ยังไม่มีบัญชี?",
    createAccount: "สร้างบัญชี",
    unverifiedNotice: "ยืนยันอีเมลก่อนเข้าสู่ระบบ",
    verifyEmail: "ไปหน้ายืนยันอีเมล",
    invalidLogin: "อีเมลหรือรหัสผ่านไม่ถูกต้อง ตรวจสอบแล้วลองอีกครั้ง",
    loginInvalidRequest: "กรอกอีเมลและรหัสผ่านให้ถูกต้อง",
    loginRateLimited: "ลองเข้าสู่ระบบหลายครั้งเกินไป รอสักครู่แล้วลองใหม่",
    loginError: "เข้าสู่ระบบไม่ได้ ตรวจสอบการเชื่อมต่อแล้วลองใหม่",
    registerTitle: "สร้างบัญชี",
    registerDescription: "เก็บโน้ตไว้ในที่เดียว",
    registerFormDescription: "สร้างบัญชีเพื่อเริ่มเขียนโน้ต",
    registerFeatureOne: "ค้นหาโน้ต",
    registerFeatureOneDescription: "ค้นหาคำในชื่อและเนื้อหาโน้ต",
    registerFeatureTwo: "แชร์โน้ต",
    registerFeatureTwoDescription: "สร้างลิงก์ให้คนอื่นอ่านโน้ต",
    nameLabel: "ชื่อ",
    namePlaceholder: "ชื่อของคุณ",
    createAccountContinue: "สร้างบัญชี",
    creatingAccount: "กำลังสร้างบัญชี…",
    hasAccount: "มีบัญชีแล้ว?",
    signInLink: "เข้าสู่ระบบ",
    verificationNotice: "เราจะส่งรหัสยืนยัน 6 หลักไปทางอีเมล",
    passwordMinLength: "อย่างน้อย 8 ตัวอักษร",
    passwordWeak: "อ่อน",
    passwordFair: "พอใช้",
    passwordGood: "ดี",
    passwordStrong: "แข็งแรง",
    emailAlreadyUsed: "อีเมลนี้มีบัญชีแล้ว เข้าสู่ระบบหรือใช้อีเมลอื่น",
    registerInvalid: "ตรวจสอบอีเมล ชื่อ และรหัสผ่านแล้วลองใหม่",
    registerRateLimited: "ส่งคำขอหลายครั้งเกินไป รอสักครู่แล้วลองใหม่",
    registerEmailUnavailable: "ส่งอีเมลยืนยันไม่ได้ ลองอีกครั้งภายหลัง",
    registerError: "สร้างบัญชีไม่ได้ ตรวจสอบการเชื่อมต่อแล้วลองใหม่",
    resetTitle: "รีเซ็ตรหัสผ่าน",
    resetDescription: "เราจะส่งรหัส 6 หลักไปทางอีเมล",
    sendResetCode: "ส่งรหัสรีเซ็ต",
    sending: "กำลังส่ง…",
    verificationCode: "รหัส 6 หลัก",
    newPassword: "รหัสผ่านใหม่",
    setNewPassword: "ตั้งรหัสผ่านใหม่",
    resetSuccess: "เปลี่ยนรหัสผ่านแล้ว เข้าสู่ระบบได้เลย",
    resetRequestSuccess: "หากมีบัญชีนี้ ระบบจะส่งรหัสรีเซ็ตไปทางอีเมล",
    resetInvalidCode: "รหัสไม่ถูกต้องหรือหมดอายุ ขอรหัสใหม่แล้วลองอีกครั้ง",
    resetRateLimited: "ลองหลายครั้งเกินไป รอสักครู่แล้วลองใหม่",
    resetError: "รีเซ็ตรหัสผ่านไม่ได้ ตรวจสอบข้อมูลแล้วลองใหม่",
    backToSignIn: "กลับไปเข้าสู่ระบบ",
    verifyTitle: "ยืนยันอีเมล",
    verifyDescription: "กรอกรหัส 6 หลักที่ส่งไปทางอีเมล",
    verifyCode: "รหัสยืนยัน",
    verify: "ยืนยันอีเมล",
    verifying: "กำลังตรวจสอบ…",
    resendCode: "ส่งรหัสใหม่",
    resendingCode: "กำลังส่ง…",
    verificationSuccess: "ยืนยันอีเมลแล้ว กำลังเข้าสู่ระบบ…",
    verificationError: "ยืนยันรหัสไม่ได้ ตรวจสอบรหัสแล้วลองใหม่",
    verificationRateLimited: "ลองยืนยันหลายครั้งเกินไป รอสักครู่แล้วลองใหม่",
    resendSuccess: "หากบัญชียังไม่ได้ยืนยัน ระบบจะส่งรหัสใหม่ให้",
    resendError: "ส่งรหัสใหม่ไม่ได้ ลองอีกครั้งภายหลัง",
    oauthInvalidTitle: "คำขอเชื่อมต่อไม่ถูกต้อง",
    oauthInvalidDescription: "ข้อมูลเชื่อมต่อไม่ครบ หรือไม่ตรงกับแอปที่ลงทะเบียนไว้",
    backToNota: "กลับไป Nota",
    oauthSignInTitle: "เข้าสู่ระบบเพื่อเชื่อมต่อ",
    oauthSignInDescription: "{client} ต้องการเชื่อมต่อกับโน้ตของคุณ เข้าสู่ระบบเพื่อตรวจสอบคำขอ",
    oauthAllowTitle: "อนุญาตให้ {client} เชื่อมต่อหรือไม่?",
    oauthAccount: "บัญชี",
    oauthRedirect: "ที่อยู่ปลายทาง",
    oauthPermissions: "สิทธิ์ที่ขอ",
    oauthReadTitle: "อ่านและค้นหาโน้ต",
    oauthReadDescription: "ดูรายการโน้ตและค้นหาจากเนื้อหา",
    oauthWriteTitle: "สร้างและแก้ไขโน้ต",
    oauthWriteDescription: "สร้างโน้ต แก้เนื้อหา และจัดการการแชร์",
    oauthFoldersTitle: "จัดการโฟลเดอร์",
    oauthFoldersDescription: "สร้าง เปลี่ยนชื่อ และลบโฟลเดอร์",
    deny: "ปฏิเสธ",
    allow: "อนุญาต",
    authorizing: "กำลังอนุญาต…",
    oauthNetworkError: "ดำเนินการไม่ได้ ตรวจสอบการเชื่อมต่อแล้วลองใหม่",
    oauthError: "ดำเนินการไม่ได้ กลับไปที่แอปแล้วลองใหม่",
    oauthSecurity: "คำขอนี้ใช้ PKCE S256 และเพิกถอนสิทธิ์ได้ที่ การตั้งค่า → MCP",
    loading: "กำลังโหลด…",
    showPassword: "แสดงรหัสผ่าน",
    hidePassword: "ซ่อนรหัสผ่าน",
    footer: "Nota · โน้ต",
    sharedNote: "โน้ตที่แชร์",
    sharedNoteUnavailableTitle: "เปิดโน้ตนี้ไม่ได้",
    sharedNoteUnavailable: "โน้ตอาจปิดการแชร์แล้ว หรือลิงก์ไม่ถูกต้อง",
    openNota: "ไปที่ Nota",
  },
} satisfies Record<Language, Record<string, string>>;

export type AuthCopy = typeof AUTH_COPY.en;

export function getLoginError(status: number, lang: Language): string {
  const copy = AUTH_COPY[lang];
  if (status === 400) return copy.loginInvalidRequest;
  if (status === 401) return copy.invalidLogin;
  if (status === 429) return copy.loginRateLimited;
  return copy.loginError;
}

export function getRegisterError(status: number, lang: Language): string {
  const copy = AUTH_COPY[lang];
  if (status === 400) return copy.registerInvalid;
  if (status === 409) return copy.emailAlreadyUsed;
  if (status === 429) return copy.registerRateLimited;
  if (status === 503) return copy.registerEmailUnavailable;
  return copy.registerError;
}
