import type { Language } from "@/shared/language";

export const I18N_MCP = {
  en: {
    checking: "Checking setup…",
    endpointReady: "MCP endpoint ready",
    endpointUnavailable: "MCP endpoint unavailable",
    cursorInstructions: "Open the link in Cursor and allow access when prompted.",
    claudeInstructions: "In Claude, open Customize → Connectors → + → Add custom connector, then paste this URL.",
    chatgptInstructions: "In ChatGPT, enable developer mode where available. Open Settings → Apps → Create, paste this URL, then scan tools.",
    mcpUrl: "MCP server URL",
    addToCursor: "Add to Cursor",
    copyUrl: "Copy MCP URL",
    copied: "Copied",
    endpointNotReady: "MCP is not ready. Check its database migrations, enabled setting, and Nota URL.",
    remoteUrlRequired: "Claude and ChatGPT need a reachable HTTPS URL. This local URL works only with a client on this device.",
    copyFailed: "Could not copy. Select the text and copy it manually.",
    cursorSetupNote: "Opening the link does not confirm setup. If it does not open, copy the URL or use this JSON config:",
    copyJson: "Copy JSON config",
    copiedJson: "JSON copied",
    claudeWorkspaceNote: "On Team and Enterprise, an Owner must add the connector first.",
    claudeGuide: "Claude setup guide",
    chatgptAvailabilityNote: "Full MCP access requires Business or Enterprise/Edu. Pro supports read and fetch tools in developer mode.",
    chatgptGuide: "ChatGPT setup guide",
    manualKeys: "API keys",
    createKey: "Create key",
    creatingKey: "Creating…",
    manualKeyDescription: "For manual HTTP or stdio setup. Copy the key now; it expires after 90 days and can be revoked here.",
    manualConfig: "Manual config",
    cursorHttp: "Cursor · HTTP",
    claudeStdio: "Claude · stdio",
    copyConfig: "Copy config",
    copiedConfig: "Config copied",
    copiedKey: "Copied",
    copyKey: "Copy key",
    createdExpires: (created: string, expires: string) => `Created ${created} · Expires ${expires}`,
    revoke: "Revoke",
    keyCreateError: "Could not create the key. Check your connection and try again.",
    keyRevokeError: "Could not revoke the key. Check your connection and try again.",
    keyStorageError: "Key storage is unavailable. Try again later.",
    keyMcpDisabled: "MCP is not enabled on this server.",
    keyVerifyEmail: "Verify your email before creating an API key.",
    keySignIn: "Your session has ended. Sign in again.",
    keyRateLimited: "Too many requests. Wait a moment and try again.",
    credentialsLoadError: "Could not load API keys. Check your connection and try again.",
  },
  th: {
    checking: "กำลังตรวจสอบ…",
    endpointReady: "MCP พร้อมใช้งาน",
    endpointUnavailable: "MCP ยังไม่พร้อม",
    cursorInstructions: "เปิดลิงก์ใน Cursor แล้วอนุญาตเมื่อแอปถาม",
    claudeInstructions: "ใน Claude ไปที่ Customize → Connectors → + → Add custom connector แล้ววาง URL นี้",
    chatgptInstructions: "ใน ChatGPT ให้เปิด developer mode หากบัญชีรองรับ จากนั้นไปที่ Settings → Apps → Create วาง URL นี้ แล้วสแกนเครื่องมือ",
    mcpUrl: "URL ของ MCP server",
    addToCursor: "Add to Cursor",
    copyUrl: "คัดลอก MCP URL",
    copied: "คัดลอกแล้ว",
    endpointNotReady: "MCP ยังไม่พร้อม ตรวจการติดตั้งตารางฐานข้อมูล การเปิด MCP และ URL ของ Nota",
    remoteUrlRequired: "Claude และ ChatGPT ต้องใช้ URL แบบ HTTPS ที่เข้าถึงได้จากอินเทอร์เน็ต URL ในเครื่องนี้ใช้ได้เฉพาะแอปบนเครื่องเดียวกัน",
    copyFailed: "คัดลอกไม่ได้ เลือกข้อความแล้วคัดลอกด้วยตนเอง",
    cursorSetupNote: "การเปิดลิงก์ยังไม่ยืนยันว่าตั้งค่าเสร็จ หากเปิดไม่ได้ ให้คัดลอก URL หรือใช้ JSON นี้:",
    copyJson: "คัดลอก JSON config",
    copiedJson: "คัดลอก JSON แล้ว",
    claudeWorkspaceNote: "แพ็กเกจ Team และ Enterprise ต้องให้ Owner เพิ่ม connector ก่อน",
    claudeGuide: "คู่มือตั้งค่า Claude",
    chatgptAvailabilityNote: "MCP แบบเต็มใช้ได้ใน Business และ Enterprise/Edu ส่วน Pro รองรับเครื่องมืออ่านและค้นหาใน developer mode",
    chatgptGuide: "คู่มือตั้งค่า ChatGPT",
    manualKeys: "API keys",
    createKey: "สร้าง key",
    creatingKey: "กำลังสร้าง…",
    manualKeyDescription: "ใช้ตั้งค่า HTTP หรือ stdio คัดลอก key หลังสร้าง เพราะจะแสดงครั้งเดียว หมดอายุใน 90 วัน และเพิกถอนได้ที่นี่",
    manualConfig: "ตั้งค่าเอง",
    cursorHttp: "Cursor · HTTP",
    claudeStdio: "Claude · stdio",
    copyConfig: "คัดลอก config",
    copiedConfig: "คัดลอก config แล้ว",
    copiedKey: "คัดลอกแล้ว",
    copyKey: "คัดลอก key",
    createdExpires: (created: string, expires: string) => `สร้างเมื่อ ${created} · หมดอายุ ${expires}`,
    revoke: "เพิกถอน",
    keyCreateError: "สร้าง key ไม่ได้ ตรวจสอบการเชื่อมต่อแล้วลองใหม่",
    keyRevokeError: "เพิกถอน key ไม่ได้ ตรวจสอบการเชื่อมต่อแล้วลองใหม่",
    keyStorageError: "พื้นที่จัดเก็บ key ใช้ไม่ได้ ลองอีกครั้งภายหลัง",
    keyMcpDisabled: "เซิร์ฟเวอร์นี้ยังไม่ได้เปิด MCP",
    keyVerifyEmail: "ยืนยันอีเมลก่อนสร้าง API key",
    keySignIn: "เซสชันหมดอายุแล้ว เข้าสู่ระบบอีกครั้ง",
    keyRateLimited: "ส่งคำขอหลายครั้งเกินไป รอสักครู่แล้วลองใหม่",
    credentialsLoadError: "โหลด API key ไม่ได้ ตรวจสอบการเชื่อมต่อแล้วลองใหม่",
  },
} satisfies Record<Language, Record<string, string | ((...args: never[]) => string)>>;
