import type { Language } from "@/shared/language";

export const I18N_DIAGRAM = {
  en: {
    loading: "Loading diagram…",
    copy: "Copy",
    copied: "Copied",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    resetView: "Reset view",
    showSource: "Show Mermaid source",
    hideSource: "Hide Mermaid source",
    copySource: "Copy Mermaid source",
    downloadSvg: "Download SVG",
    downloadPng: "Download PNG",
    exitFullscreen: "Exit fullscreen",
    fullscreen: "Open fullscreen",
    syntaxError: "Mermaid syntax error",
    copyError: "Copy error details",
    copyFailed: "Could not copy. Show the source and select it manually.",
    exportFailed: "Could not export this diagram. Try downloading SVG.",
    source: "Mermaid source",
    dragHint: "Drag to move · Ctrl + wheel to zoom",
    wheelHint: "Drag to move · Scroll to zoom · Esc to exit",
    vector: "SVG",
  },
  th: {
    loading: "กำลังโหลดแผนภาพ…",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    zoomIn: "ซูมเข้า",
    zoomOut: "ซูมออก",
    resetView: "รีเซ็ตมุมมอง",
    showSource: "ดูโค้ด Mermaid",
    hideSource: "ซ่อนโค้ด Mermaid",
    copySource: "คัดลอกโค้ด Mermaid",
    downloadSvg: "ดาวน์โหลด SVG",
    downloadPng: "ดาวน์โหลด PNG",
    exitFullscreen: "ออกจากเต็มจอ",
    fullscreen: "ขยายเต็มจอ",
    syntaxError: "ไวยากรณ์ Mermaid ไม่ถูกต้อง",
    copyError: "คัดลอกรายละเอียดข้อผิดพลาด",
    copyFailed: "คัดลอกไม่ได้ เปิดดูต้นฉบับแล้วเลือกข้อความเพื่อคัดลอก",
    exportFailed: "ส่งออกแผนภาพไม่ได้ ลองดาวน์โหลดเป็น SVG",
    source: "โค้ด Mermaid",
    dragHint: "ลากเพื่อเลื่อน · กด Ctrl แล้วหมุนล้อเมาส์เพื่อซูม",
    wheelHint: "ลากเพื่อเลื่อน · หมุนล้อเมาส์เพื่อซูม · กด Esc เพื่อออก",
    vector: "SVG",
  },
} satisfies Record<Language, Record<string, string>>;
